version: '3.9' # Secrets kullanmak için 3.1 ve üzeri bir versiyon kullanın

services:
  # Veritabanı Servisi
  db:
    image: postgres:15-alpine
    environment:
      # PostgreSQL, bu değişkeni kullanır. Değişkenin değeri Secret'tan gelecek.
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_root_password
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      replicas: 1

    secrets:
      - postgres_root_password  # Yaratttığımız Secret'ı buraya bağlıyoruz

  # Uygulama Servisi (Veritabanına bağlanacak olan)
  app:
    image: alpine/curl
    command: sh -c "sleep 10 && ls -l /run/secrets"
    depends_on:
      - db
    secrets:
      - postgres_root_password  # Bu servis de Secret'a erişebilmeli

secrets:
  postgres_root_password:
    external: true # Bu Secret'ın dışarıdan (yani docker secret create ile) yaratıldığını belirtir

volumes:
  db-data:


# YAML'daki Önemli Noktalar:

#  secrets: (En altta): Dışarıdan oluşturduğumuz Secret'ı tanımladık.

#  secrets: (Servis içinde): Bu servisin hangi Secret'a erişebileceğini belirledik.

#  POSTGRES_PASSWORD_FILE: Bu ortam değişkeni, PostgreSQL'e şifreyi değişken olarak almak yerine, hangi dosyanın içinden okuması gerektiğini söyler.

#  /run/secrets/postgres_root_password: Secret, container içinde bu adreste dosya olarak belirir. Uygulama bu dosyanın içeriğini okuyarak şifreye ulaşır.